# Generated by Django 3.1.5 on 2021-01-30 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotSystGenus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lac_name', models.CharField(max_length=32, verbose_name='Nazwa łacińska')),
                ('pl_name', models.CharField(max_length=32, verbose_name='Nazwa polska')),
                ('hybrid', models.BooleanField(null=True, verbose_name='Mieszaniec')),
            ],
        ),
        migrations.CreateModel(
            name='BotSystSpecies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lac_name', models.CharField(max_length=32, verbose_name='Nazwa łacińska')),
                ('pl_name', models.CharField(max_length=32, verbose_name='Nazwa polska')),
                ('hybrid', models.BooleanField(null=True, verbose_name='Mieszaniec')),
                ('genus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botanical.botsystgenus')),
            ],
        ),
        migrations.CreateModel(
            name='BotSystCultivar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cultivar', models.CharField(max_length=32, verbose_name='Odmiana')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botanical.botsystspecies')),
            ],
        ),
    ]
