# Generated by Django 3.1.5 on 2021-02-01 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botanical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantBodyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_type', models.CharField(max_length=32)),
                ('lp', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PlntLibraries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edible', models.BooleanField(default=False)),
                ('body_type', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='botanical.plantbodytype')),
                ('cultivar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='botanical.botsystcultivar')),
                ('genus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botanical.botsystgenus')),
                ('species', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='botanical.botsystspecies')),
            ],
        ),
    ]
