# Generated by Django 3.1.5 on 2021-02-02 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botanical', '0003_auto_20210202_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantDescriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('botanical', models.TextField()),
                ('cultivation', models.TextField()),
                ('destiny', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='plntlibraries',
            name='description',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='botanical.plantdescriptions'),
        ),
    ]
