# Generated by Django 3.1.5 on 2021-02-02 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botanical', '0004_auto_20210202_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plntlibraries',
            name='description',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='botanical.plantdescriptions'),
        ),
    ]
