# Generated by Django 3.1.5 on 2021-02-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botanical', '0005_auto_20210202_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantdescriptions',
            name='botanical',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='plantdescriptions',
            name='cultivation',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='plantdescriptions',
            name='destiny',
            field=models.TextField(null=True),
        ),
    ]
